[package]
name = "backend_redpiler"
authors.workspace = true
description.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
readme.workspace = true
version.workspace = true
license.workspace = true
repository.workspace = true
include.workspace = true

[dependencies]
mchprs_backend_lib = { path = "../../crates/backend_lib" }